version: '3'

services:
  mysql:
    build:
      context: compose/db/
      dockerfile: DOCKERFILE
    env_file:
      - ./compose/db/.env # Revisar si esta ruta debe ser relativa al contexto o al compose
    expose:
      - "3306"
    command: ["mysqld"]


  nodejs:
    build:
      context: .
      dockerfile: compose/goodreads/DOCKERFILE
    container_name: nodejs-container
    env_file:
      - ./compose/goodreads/.env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
