const settings = {
    SECRET_KEY: process.env.SECRET_KEY,

    PORT: process.env.PORT,

    DATABASE_HOST: process.env.DATABASE_HOST,
    DATABASE_USER: process.env.DATABASE_USER,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    DATABASE_NAME: process.env.DATABASE_NAME,
    DATABASE_WAIT_FOR_CONNECTIONS: process.env.DATABASE_WAIT_FOR_CONNECTIONS,
    DATABASE_CONNECTION_LIMIT: process.env.DATABASE_CONNECTION_LIMIT,
    DATABASE_QUEUE_LIMIT: process.env.DATABASE_QUEUE_LIMIT
}

module.exports = settings;
